variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  
stages:
  - build

build-development-cantaloupe:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - cantaloupe/VERSION
      when: never 
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - cantaloupe/**/*
      when: always
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/cantaloupe:$CI_COMMIT_SHORT_SHA ./cantaloupe
    - docker build -t $CI_REGISTRY_IMAGE/cantaloupe:latest-dev ./cantaloupe
    - docker push $CI_REGISTRY_IMAGE/cantaloupe:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/cantaloupe:latest-dev


build-production:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\..*$/
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - IMAGE_TAG=$(echo $CI_COMMIT_TAG | awk 'match($0, /v(.*)/) {print substr($0, RSTART+1, RLENGTH-1)}')
  script:
    - docker build -f Dockerfile.production -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker build -f Dockerfile.production -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest