language: ruby
rvm:
  - 2.4.5

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle exec rake db:setup RAILS_ENV=test
  - solr_wrapper -v -d solr/config/ -n hydra-test -p 8985
  - fcrepo_wrapper -v -p 8986 --no-jms

cache:
  bundler: true

services:
  - postgresql
  - redis-server

jdk:
  - oraclejdk8