language: ruby
rvm:
  - 2.4.5

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle exec rake db:setup RAILS_ENV=test

script:
  - bundle exec rake ci

cache:
  bundler: true

services:
  - postgresql
  - redis-server

jdk:
  - oraclejdk8