version: '3'

services:
  app:
    build: .
    entrypoint: 'docker-entrypoint.sh'
    command: ['rails',  's',  '-p', '3000', '-b', '0.0.0.0']
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./ingest_packages:/ingest_packages
      - .:/armand-app
    depends_on:
      - db
      - fcrepo
      - redis
      - solr
      - cantaloupe
      - memcached
      - workers

  db:
    image: postgres:13
    restart: always
    environment: 
      - POSTGRES_USER=armand
      - POSTGRES_PASSWORD=armand
      - POSTGRES_DB=armand_development
    volumes:
      - db:/var/lib/postgresql/data

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    restart: always
    volumes:
      - fcrepo:/data:cached
    ports:
      - 8080:8080

  memcached:
    image: bitnami/memcached

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redis:/data

  solr:
    image: solr:6.6
    restart: always
    ports:
      - 8983:8983
    volumes:
      - solr:/opt/solr/server/solr

  cantaloupe:
    image: seanlw/cantaloupe:latest
    restart: always
    env_file: .env
    environment: 
      - JAVA_OPTS=-Xmx2g
    ports:
      - 8182:8182
    volumes:
      - cantaloupe-cache:/cantaloupe/cache
    depends_on: 
      - fcrepo

  workers:
    build: .
    restart: always
    env_file: .env
    environment: 
      - DISABLE_REDIS_CLUSTER=true
    command: ["bundle", "exec", "sidekiq", "-q", "default"]
    volumes:
      - ./ingest_packages:/ingest_packages
      - .:/armand-app
    depends_on:
      - db
      - fcrepo
      - redis
      - solr

volumes:
  db:
  fcrepo:
  redis:
  solr:
  cantaloupe-cache:

