# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d5e2c5917b072424813112d4bea48ef3390bf6b31ab31341292115ebc2a886fadecfb85c4acb0686525d410481db5514e9d6734c4fa733163743d6069aacaa4

test:
  secret_key_base: 74169b70bcd5269be493653f2270ca2c58dd1047fd705edd5daab9e68534af9cdd4dbf071fc2fbfd37a9160a425df616db1f42aeca8f58d785896f4c194733b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
