fits_path: "/opt/fits/fits.sh"

armand:
  name: Repository Name
  host: example.com
  oai_url: http://example.com/catalog/oai
  oai_prefix: 'oai:localhost'
  oai_admin_email: 'admin@localhost'

hybridge:
  filesystem: /var/ingest
  aspace_frontend_url: http://aspace.example.com

greens:
  base_url: http://example.com/
  endpoint: http://example.com/api/
  prefix: do
  api_key: 0000

aspace:
  endpoint: http://example.com:8089
  username: aspace
  password: password

active_job:
  queue_adapter: :sidekiq

cas:
  active: false
  base_url: https://cas.example.com
  validate_url: https://cas.example.com/p3/serviceValidate
  create_user: true
  email_attribute: :email

campus_ip: 
  - 192.168.1.0/24

iiif:
  endpoint_url: http://iiif.example.com:8182/iiif/2

email:
  default_from: someone@example.com
  to: someone@example.com
  delivery_method: :smtp
  smtp:
    address: smtp.example.com
    port: 25
    enable_starttls_auto: false