fits_path: "/opt/fits/fits.sh"

derivatives:
  path: <%= Rails.root.join('tmp', 'derivatives') %>
  tmp: <%= Rails.root.join('tmp', 'derivatives', 'tmp') %>

uploads:
  path: <%= Rails.root.join('tmp', 'uploads') %>

armand:
  name: Repository Name
  host: example.com
  oai_url: http://example.com/catalog/oai
  oai_prefix: "oai:localhost"
  oai_admin_email: "admin@localhost"

hybridge:
  filesystem: /var/ingest
  aspace_frontend_url: http://aspace.example.com

greens:
  base_url: http://example.com/
  endpoint: http://example.com/api/
  prefix: do
  api_key: 0000

aspace:
  endpoint: http://example.com:8089
  username: aspace
  password: password

active_job:
  queue_adapter: :sidekiq

saml:
  active: true
  assertion_consumer_service_url: "http://localhost:3000/users/saml/auth"
  assertion_consumer_service_binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
  name_identifier_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
  sp_entity_id: "http://localhost:3000/users/saml/metadata"
  authn_context: "urn:oasis:names:tc:SAML:2.0:ac:classes:Password"
  security_assertions_encrypted: false
  idp_sso_service_url: "http://localhost:8888/simplesaml/saml2/idp/SSOService.php"
  idp_slo_service_url: "http://localhost:8888/simplesaml/saml2/idp/SingleLogoutService.php"
  idp_cert:
    -----BEGIN CERTIFICATE-----
    MIICmjCCAYICCQDX5sKPsYV3+jANBgkqhkiG9w0BAQsFADAPMQ0wCwYDVQQDDAR0
    ZXN0MB4XDTE5MTIyMzA5MDI1MVoXDTIwMDEyMjA5MDI1MVowDzENMAsGA1UEAwwE
    dGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMdtDJ278DQTp84O
    5Nq5F8s5YOR34GFOGI2Swb/3pU7X7918lVljiKv7WVM65S59nJSyXV+fa15qoXLf
    sdRnq3yw0hTSTs2YDX+jl98kK3ksk3rROfYh1LIgByj4/4NeNpExgeB6rQk5Ay7Y
    S+ARmMzEjXa0favHxu5BOdB2y6WvRQyjPS2lirT/PKWBZc04QZepsZ56+W7bd557
    tdedcYdY/nKI1qmSQClG2qgslzgqFOv1KCOw43a3mcK/TiiD8IXyLMJNC6OFW3xT
    L/BG6SOZ3dQ9rjQOBga+6GIaQsDjC4Xp7Kx+FkSvgaw0sJV8gt1mlZy+27Sza6d+
    hHD2pWECAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAm2fk1+gd08FQxK7TL04O8EK1
    f0bzaGGUxWzlh98a3Dm8+OPhVQRi/KLsFHliLC86lsZQKunYdDB+qd0KUk2oqDG6
    tstG/htmRYD/S/jNmt8gyPAVi11dHUqW3IvQgJLwxZtoAv6PNs188hvT1WK3VWJ4
    YgFKYi5XQYnR5sv69Vsr91lYAxyrIlMKahjSW1jTD3ByRfAQghsSLk6fV0OyJHyh
    uF1TxOVBVf8XOdaqfmvD90JGIPGtfMLPUX4m35qaGAU48PwCL7L3cRHYs9wZWc0i
    fXZcBENLtHYCLi5txR8c5lyHB9d3AQHzKHMFNjLswn5HsckKg83RH7+eVqHqGw==
    -----END CERTIFICATE-----

campus_ip:
  - 192.168.1.0/24

iiif:
  endpoint_url: http://iiif.example.com:8182/iiif/2

email:
  default_from: someone@example.com
  to: someone@example.com
  delivery_method: :smtp
  smtp:
    address: smtp.example.com
    port: 25
    enable_starttls_auto: false

google_analytics_tracking_id: ''