fits_path: "/opt/fits/fits.sh"

armand:
  host: example.com

hybridge:
  filesystem: /var/ingest
  aspace_frontend_url: http://aspace.example.com

greens:
  base_url: http://example.com
  endpoint: http://example.com/api/
  prefix: do
  api_key: 0000