# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  property :alto_data, predicate: ::RDF::URI.new("https://vocab.lib.uh.edu/bcdams-map#alto"), multiple: false
end
